### PR TITLE
Load config in subber.py

### LINKED ISSUE #42: Load config in subber.py
Thank you for your contribution to Subber! Please fill out one of the two templates below (issue or feature request).

### Feature request (please include as much detail as possible):

The config file should be loaded in `subber.py` and rather than doing so directly from the Reddit class in `reddit.py`.

This addresses the confusing import system for the unit tests in #41

### PR DESCRIPTION
**Pull request by trevormccasland**
This commit aims to refactor config loading so it is loaded in
subber.py instead of reddit.py

Closes #42

### CODE REVIEW

**Comment by trevormccasland** [comment]
Looks like an unrelated failure in the container run process 😢

**Comment by drewwalters96** [comment]
@trevormccasland, it appears to be a unit test that is failing:

```
test_get_user_recommendations (tests.test_reddit.TestReddit) ... ok
Traceback (most recent call last):
  File "/home/travis/build/drewwalters96/subber/subber/config.py", line 43, in get_config
    with open(config_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'subber.cfg'
```

**Comment by trevormccasland** [comment]
I had a subber.cfg in my home directory, that's why the tests were passing locally, so I just need to replicate that in the tests somehow.

**Comment by drewwalters96** [comment]
Thank you, @trevormccasland! Please let me know if you object to having your commits squashed upon merge so that Subber does not fail to build on intermediary commits.

**Pull request merged**
